In [12]:
import keras
import numpy as np
import pickle

In [13]:
class Fonts:
    def __init__(self, name, d):
        self.name = name
        self.d = d

f = open("savedFonts", 'r')
fonts = pickle.load(f)

In [55]:
commands = []
for i, font in enumerate(fonts):
    commands.append([])
    for command in font.d:
        commands[i].append(command[0])

In [69]:
print commands

[['M', 'q', 't', 't', 't', 'q', 't', 't', 't', 'z', 'M', 'v', 'q', 't', 't', 'h', 'v', 'h', 'v', 'h', 'q', 't', 't', 'v', 'q', 't', 't', 'h', 'v', 'q', 'h', 'z'], ['M', 'l', 'h', 'v', 'h', 'v', 'z', 'M', 'q', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 'z'], ['M', 'q', 'v', 'h', 'v', 'q', 'v', 'q', 'v', 'h', 'v', 'z', 'M', 'q', 't', 'q', 't', 't', 't', 'q', 't', 't', 't', 'z'], ['M', 'q', 't', 'q', 't', 'q', 't', 'q', 't', 'z', 'M', 'l', 'h', 'v', 'h', 'v', 'z'], ['M', 'q', 'q', 't', 'q', 't', 'z', 'M', 'q', 'q', 'q', 'l', 'q', 'q', 'q', 'q', 't', 'l', 'q', 't', 'l', 'q', 'q', 'q', 'q', 'l', 'q', 'q', 'q', 'v', 'q', 't', 'q', 'q', 'z'], ['M', 'q', 't', 't', 't', 'q', 't', 't', 't', 't', 't', 't', 't', 'q', 't', 't', 't', 'z', 'M', 'l', 'h', 'v', 'h', 'v', 'z'], ['M', 'l', 'h', 'v', 'h', 'v', 'z', 'M', 'q', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 'z'], ['M', 'q', 't', 't', 't', 't', 't', 't', 't', 'z', 'M', 'h', 'v', 'h',

In [62]:
#Remove long commands
maxCommandLen = 50
count = 0
for command in commands:
    if len(command) > maxLen:
        commands.remove(command)
        count += 1
        
print 'Removed: ', count
print 'Max Len', max([len(command) for command in commands])

Removed:  0
Max Len 50


In [63]:
#There are no other upper cased commands
for command in commands:
    for c in command:
        if c != 'M' and c.isupper():
            print c

In [65]:
#Create dictionary for mapping to one hot vectors
commandList = ['M','m','l','h','v','z','c','s','q','t','a']
oneHotMap = {}
for i, c in enumerate(commandList):
    oneHotMap[c] = i

In [67]:
#X train
X = np.zeros((len(commands), maxCommandLen, len(commandList)))

In [70]:
for i, command in enumerate(commands):
    for j, c in enumerate(command):
        X[i, j, oneHotMap[c]] = 1

In [71]:
print X

[[[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 1. 0. 0.]
  [0. 0. 0. ... 0. 1. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 1. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 1. 0. 0.]
  [0. 0. 0. ... 0. 1. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
